name: Build and Deploy
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
     - name: Get code
       uses: actions/checkout@v4
     - name: Install deps
       run: npm ci
     - name: Build project
       run: npm run build
     - name: Upload Artifact
       uses: actions/upload-artifact@v4
       with:
         name: build-files
         path: build
  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Get build project
        uses: actions/download-artifact@v4
        with:
          name: build-files